# Original Code by Physanus
# Modified by WarpWing 
version: "3"
  services: 
    dockergen: 
      command: "-notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
      container_name: nginx-docker-gen
      image: jwilder/docker-gen
      volumes: 
        - "nginx-config:/etc/nginx/conf.d"
        - "nginx-certs:/etc/nginx/certs"
        - "nginx-vhosts:/etc/nginx/vhost.d"
        - "nginx-webroot:/usr/share/nginx/html"
        - "nginx-well-known:/usr/share/nginx/html/.well-known"
        - "/var/run/docker.sock:/tmp/docker.sock:ro"
        - "./config/dockergen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl"
    letsencrypt: 
      container_name: letsencrypt
      environment: 
        NGINX_DOCKER_GEN_CONTAINER: nginx-docker-gen
        NGINX_PROXY_CONTAINER: nginx
      image: jrcs/letsencrypt-nginx-proxy-companion
      volumes: 
        - "nginx-config:/etc/nginx/conf.d"
        - "nginx-certs:/etc/nginx/certs"
        - "nginx-vhosts:/etc/nginx/vhost.d"
        - "nginx-webroot:/usr/share/nginx/html"
        - "nginx-well-known:/usr/share/nginx/html/.well-known"
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
    nginx: 
      container_name: nginx
      image: nginx
      ports: 
        - "80:80"
        - "443:443"
        - "3012:3012"
      restart: always
      volumes: 
        - "nginx-config:/etc/nginx/conf.d"
        - "nginx-main-config:/etc/nginx"
        - "nginx-certs:/etc/nginx/certs"
        - "nginx-vhosts:/etc/nginx/vhost.d"
        - "nginx-webroot:/usr/share/nginx/html"
        - "nginx-well-known:/usr/share/nginx/html/.well-known"

      mongo:
      image: mongo:latest
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - ./data:/data/db
      restart: always
      logging:
        driver: "none"

     redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"
      restart: always
      logging:
        driver: "none"

    skyblock-stats: 
      container_name: skyblock-stats
      environment: 
        API_KEY: "<Use your own API key - WarpWing>"
        LETSENCRYPT_EMAIL: professornitro@gmail.com
        LETSENCRYPT_HOST: skyblock.domain.tld
        VIRTUAL_HOST: skyblock.domain.tld
      image: warpwing/skycrypt:latest
      restart: always
      volumes: 
        nginx-certs: ~
        nginx-config: ~
        nginx-main-config: ~
        nginx-vhosts: ~
        nginx-webroot: ~
        nginx-well-known: 
          driver: local 

